import type { MetricFilters } from "./filters";
export type ServiceMetricRow = {
  id: string;
  organisationId: string;
  client: string;
  service: string;
  start: string;
  end: string;
  awaiting: string;
  endDate: string | null;
};
export type RevenueSummary = {
  active: string;
  awaiting: string;
  start: string;
  new: string;
  expansion: string;
  reactivation: string;
  contraction: string;
  churn: string;
  cohort: string;
  retained: string;
  capped: string;
  cohortEnd: string;
  signedOneOff: string;
  signedDeals: string;
  totalRows: number;
  rows: ServiceMetricRow[];
};
export type ReceivableRow = {
  id: string;
  organisationId: string;
  client: string;
  number: string | null;
  issuedDate: string | null;
  dueDate: string | null;
  gross: string;
  paid: string;
  credit: string;
  remaining: string;
  daysLate: number | null;
  paymentState: string;
  dispute: boolean;
  owner: string;
  fullyPaidAt: string | null;
};
export type ReceivableSummary = {
  outstanding: string;
  overdue: string;
  eligible: string;
  onTime: string;
  unknownPunctuality: number;
  totalRows: number;
  ageing: { band: string; total: string }[];
  rows: ReceivableRow[];
};
export type ExceptionRow = {
  id: string;
  organisationId: string | null;
  client: string;
  reason: string;
  since: string;
  owner: string;
  href: string;
  nextStep: string;
  severity: number;
};
export type MetricsSnapshot = {
  definitionVersion: string;
  generatedAt: string;
  filters: MetricFilters;
  revenue: RevenueSummary;
  receivables: ReceivableSummary | null;
  cash: string | null;
  lastReconciledAt: string | null;
  freshness: "unknown" | "stale" | "current";
  correctedAt: string | null;
  exceptions: ExceptionRow[];
  exceptionCount: number;
  requests: { status: string; count: number }[];
  milestones: {
    id: string;
    organisationId: string;
    title: string;
    owner: string;
    date: string;
  }[];
  milestoneCount: number;
  limitations: string[];
};
